// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ClinicaServer.Models
{
    public partial class Examegeral
    {
        public uint Id { get; set; }
        public uint Atendimentoid { get; set; }
        public uint Pressaosistolica { get; set; }
        public uint Pressaodiastolica { get; set; }
        public uint Pulsacao { get; set; }
        public uint Respiracao { get; set; }
        public float Temperatura { get; set; }
        public bool Concluido { get; set; }
        public virtual Atendimento Atendimento { get; set; }
    }
}