// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ClinicaServer.Models
{
    public partial class Examecovid
    {
        public uint Id { get; set; }
        public uint Atendimentoid { get; set; }
        public bool Febre { get; set; }
        public bool Coriza { get; set; }
        public bool Narizentupido { get; set; }
        public bool Cansaco { get; set; }
        public bool Tosse { get; set; }
        public bool Dordecabeca { get; set; }
        public bool Doresnocorpo { get; set; }
        public bool Malestargeral { get; set; }
        public bool Dordegarganta { get; set; }
        public bool Dificuldadederespirar { get; set; }
        public bool Faltadepaladar { get; set; }
        public bool Faltadeolfato { get; set; }
        public bool Dificuldadedelocomocao { get; set; }
        public bool Diarreia { get; set; }
        public bool? Concluido { get; set; }
        public virtual Atendimento Atendimento { get; set; }
    }
}