// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ClinicaServer.Models
{
    public partial class Paciente
    {
        public Paciente()
        {
            Atendimento = new HashSet<Atendimento>();
        }

        public uint Id { get; set; }
        public ulong Cpf { get; set; }
        public string Nome { get; set; }
        public DateTime Datanascimento { get; set; }
        public ulong Telefone { get; set; }
        public string Urlimagem { get; set; }
        public virtual ICollection<Atendimento> Atendimento { get; set; }
    }
}